#!/bin/bash
## Submit job to our class's allocation
# PBS -A drh20_a_g_sc_default
## Alternatively could comment out line above (by adding a second # at the beginning of the line)
## and uncomment the lines below (by removing one #) to use the "Open" allocation
##PBS -A open
## Time requested: 0 hours, 5 minutes, 0 seconds
#PBS -l walltime=00:45:00
## Ask for one core on one node
#PBS -l nodes=1:ppn=1
## Each processors will use no more than 1GB of RAM
#PBS -l pmem=1gb
## combine STDOUT and STDERR into one file
#PBS -j oe
## Specifices job name, so easy to find in qstat
#PBS -N test_job

echo "Starting job $PBS_JOBNAME"
date
echo "Job id: $PBS_JOBID"
echo "Job arrayid: $PBS_ARRAYID"

echo "Loading modules to provide Julia 1.6.2"
# module load anaconda3
# module use /gpfs/group/RISE/sw7/modules
# module load julia/1.6.0
# export LD_LIBRARY_PATH=/gpfs/group/RISE/sw7/julia-1.6.0/julia-1.6.0/lib

echo "About to change into $PBS_O_WORKDIR"
cd $PBS_O_WORKDIR            # Change into directory where job was submitted 

date
echo "About to start Julia"
julia --project test.jl
echo "Julia exited"
date